//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service_CreateNumberAndTestPrimality.PrimeNumberTester {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/Service_TestPrimeNumber")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PrimeNumberTester.ITestPrimeNumber")]
    public interface ITestPrimeNumber {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITestPrimeNumber/GetData", ReplyAction="http://tempuri.org/ITestPrimeNumber/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITestPrimeNumber/GetData", ReplyAction="http://tempuri.org/ITestPrimeNumber/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITestPrimeNumber/GetDataUsingDataContract", ReplyAction="http://tempuri.org/ITestPrimeNumber/GetDataUsingDataContractResponse")]
        Service_CreateNumberAndTestPrimality.PrimeNumberTester.CompositeType GetDataUsingDataContract(Service_CreateNumberAndTestPrimality.PrimeNumberTester.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITestPrimeNumber/GetDataUsingDataContract", ReplyAction="http://tempuri.org/ITestPrimeNumber/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<Service_CreateNumberAndTestPrimality.PrimeNumberTester.CompositeType> GetDataUsingDataContractAsync(Service_CreateNumberAndTestPrimality.PrimeNumberTester.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITestPrimeNumber/TestIfIsPrimeNumber", ReplyAction="http://tempuri.org/ITestPrimeNumber/TestIfIsPrimeNumberResponse")]
        bool TestIfIsPrimeNumber(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITestPrimeNumber/TestIfIsPrimeNumber", ReplyAction="http://tempuri.org/ITestPrimeNumber/TestIfIsPrimeNumberResponse")]
        System.Threading.Tasks.Task<bool> TestIfIsPrimeNumberAsync(int value);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITestPrimeNumberChannel : Service_CreateNumberAndTestPrimality.PrimeNumberTester.ITestPrimeNumber, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TestPrimeNumberClient : System.ServiceModel.ClientBase<Service_CreateNumberAndTestPrimality.PrimeNumberTester.ITestPrimeNumber>, Service_CreateNumberAndTestPrimality.PrimeNumberTester.ITestPrimeNumber {
        
        public TestPrimeNumberClient() {
        }
        
        public TestPrimeNumberClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TestPrimeNumberClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TestPrimeNumberClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TestPrimeNumberClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public Service_CreateNumberAndTestPrimality.PrimeNumberTester.CompositeType GetDataUsingDataContract(Service_CreateNumberAndTestPrimality.PrimeNumberTester.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<Service_CreateNumberAndTestPrimality.PrimeNumberTester.CompositeType> GetDataUsingDataContractAsync(Service_CreateNumberAndTestPrimality.PrimeNumberTester.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
        
        public bool TestIfIsPrimeNumber(int value) {
            return base.Channel.TestIfIsPrimeNumber(value);
        }
        
        public System.Threading.Tasks.Task<bool> TestIfIsPrimeNumberAsync(int value) {
            return base.Channel.TestIfIsPrimeNumberAsync(value);
        }
    }
}
